service: rs-cart-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  profile: personalAccount
  stage: dev
  region: us-west-1

plugins:
  - serverless-offline

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
